var searchData=
[
  ['stellanet_64',['StellaNet',['../md__r_e_a_d_m_e.html',1,'']]],
  ['normalize_65',['normalize',['../namespace_stella_net_1_1normalize.html',1,'StellaNet']]],
  ['show_5flayer_5fnames_66',['show_layer_names',['../namespace_stella_net_1_1stella__net__trainer.html#ae1979f9585dae24044a6556103fa071d',1,'StellaNet::stella_net_trainer']]],
  ['show_5fshapes_67',['show_shapes',['../namespace_stella_net_1_1stella__net__trainer.html#aab83a12d530d86c7ef0270604251c97a',1,'StellaNet::stella_net_trainer']]],
  ['spectra_5finput_68',['spectra_input',['../namespace_stella_net_1_1stella__net__trainer.html#ae9652a98c3976aac55b8cad259cc1b6f',1,'StellaNet::stella_net_trainer']]],
  ['spectrum_69',['Spectrum',['../class_stella_net_1_1spectrum_1_1_spectrum.html',1,'StellaNet.spectrum.Spectrum'],['../namespacespectrum.html',1,'spectrum'],['../namespace_stella_net_1_1spectrum.html',1,'StellaNet.spectrum']]],
  ['spectrum_2epy_70',['spectrum.py',['../spectrum_8py.html',1,'']]],
  ['spectrum_5ffile_71',['spectrum_file',['../namespace_stella_net_1_1normalize.html#a7a62809fb83768b27713ac0d582ed646',1,'StellaNet::normalize']]],
  ['splinenormalize_72',['SplineNormalize',['../class_stella_net_1_1spectrum_1_1_spectrum.html#a78cc06112fe62f02c5b20e93a5d0606e',1,'StellaNet::spectrum::Spectrum']]],
  ['stella_5fnet_73',['stella_net',['../namespace_stella_net_1_1stella__net.html',1,'StellaNet']]],
  ['stella_5fnet_2epy_74',['stella_net.py',['../stella__net_8py.html',1,'']]],
  ['stella_5fnet_5fconfig_75',['stella_net_config',['../namespacestella__net__config.html',1,'stella_net_config'],['../namespace_stella_net_1_1stella__net__config.html',1,'StellaNet.stella_net_config']]],
  ['stella_5fnet_5fconfig_2epy_76',['stella_net_config.py',['../stella__net__config_8py.html',1,'']]],
  ['stella_5fnet_5fexceptions_77',['stella_net_exceptions',['../namespacestella__net__exceptions.html',1,'stella_net_exceptions'],['../namespace_stella_net_1_1stella__net__exceptions.html',1,'StellaNet.stella_net_exceptions']]],
  ['stella_5fnet_5fexceptions_2epy_78',['stella_net_exceptions.py',['../stella__net__exceptions_8py.html',1,'']]],
  ['stella_5fnet_5fpredict_79',['stella_net_predict',['../namespace_stella_net_1_1stella__net__predict.html',1,'StellaNet']]],
  ['stella_5fnet_5fpredict_2epy_80',['stella_net_predict.py',['../stella__net__predict_8py.html',1,'']]],
  ['stella_5fnet_5ftrainer_81',['stella_net_trainer',['../namespace_stella_net_1_1stella__net__trainer.html',1,'StellaNet']]],
  ['stella_5fnet_5ftrainer_2epy_82',['stella_net_trainer.py',['../stella__net__trainer_8py.html',1,'']]],
  ['stellanet_83',['StellaNet',['../namespace_stella_net.html',1,'']]],
  ['utilities_84',['utilities',['../namespace_stella_net_1_1utilities.html',1,'StellaNet']]]
];
